name: 'rss-to-readme'
description: 'Converts an RSS feed to a README.md file'
author: 'xiaotianxt'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  feed-url:
    description: 'RSS feed URL'
    required: true

# Define your outputs here.
outputs:
  feed:
    description: 'Feed'

runs:
  using: node20
  main: dist/index.js
